apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-app
  namespace: realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-app
  template:
    metadata:
      labels:
        app: realtime-app
    spec:
      containers:
        - name: realtime-app
          image: srinu298/realtime-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/realtime_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: sree!
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: realtime-app
  namespace: realtime
spec:
  selector:
    app: realtime-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31265
